### ISSUE TITLE
no longer compatible with latest version of IntelliJ

### ISSUE THREAD

**Issue by mverdicchio** [akainth015/ambient#13]
Not compatible with the version of your running IDE (IntelliJ IDEA 2021.3.1)
Compatible with IntelliJ IDEA (Ultimate, Community, Educational), Android Studio

Hoping for an update. Thanks for all you've done so far.

**Comment by akainth015** [comment]
Sure, I've released an update for the plugin. It should be available within 48 hours.

**Comment by akainth015** [comment]
The updated plugin is available in IntelliJ 2021.3.1
