### ISSUE TITLE
Community Edition

### ISSUE THREAD

**Issue by mverdicchio** [akainth015/ambient#14]
Hi,
I have a couple of students using the community edition and Ambient doesn't appear in the marketplace search, but it does for Ultimate edition. I've advised them to upgrade but I was wondering if there was a simple fix to allow the plugin to be installed for community edition also. Thanks.

**Comment by akainth015** [comment]
I'm not sure what the issue is, Ambient is compiled against the community edition and I was able to locate it in the marketplace on IntelliJ IDEA Community 2021.3.3
